version: '3.8'

services:
  consumer:
    build: ./consumer
    command: [python, main.py]
    env_file:
      - './consumer/.env'
    volumes:
      - ./consumer:/app/consumer


  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8090:8080
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=ms-notifications
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=url
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_PLAINTEXT
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=PLAIN
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.scram.ScramLoginModule required username='user' password='jora';
      - KAFKA_CLUSTERS_0_PROPERTIES_PROTOCOL=SASL
    # links:
    #   - zookeeper
